apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansah-e-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ansah-e-backend
  template:
    metadata:
      labels:
        app: ansah-e-backend
    spec:
      containers:
      - name: ansah-e-backend
        image: ansah-e-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-server
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-db
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

